//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intprog2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogr
    {
        public int ogrId { get; set; }
        public string ogrAdsoyad { get; set; }
        public string ogrMail { get; set; }
        public string ogrNo { get; set; }
        public string ogrSoru { get; set; }
    
        public virtual soru soru { get; set; }
    }
}
