//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intprog2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrt
    {
        public int ogrtId { get; set; }
        public string ogrtMail { get; set; }
        public string ogrtAdsoyad { get; set; }
        public string ogrtNo { get; set; }
        public string ogrtYanıt { get; set; }
    
        public virtual soru soru { get; set; }
    }
}
